#!/bin/bash
set -e
RUNNER_ARCH="${TARGETARCH:-$(arch)}"
RUNNER_HOME=/home/runner

get_latest_tag() {
  local github_repo="$1"
  curl -I -s \
      --retry-max-time "${RETRY_MAX_TIME:-60}" \
      --retry "${RETRIES:-3}" \
      --retry-connrefused \
      "https://github.com/${github_repo}/releases/latest" 2>&1 |
    sed -n '/^location:/ { s/location: https.*tag\///; p }' | tr -d '\n\r'
}

install_runner() {
  local arch="" version="" current_version="" latest_version=""
  latest_version="$(get_latest_tag 'actions/runner')"
  latest_version="${latest_version#v}"
  current_version="$(cat "$RUNNER_HOME/.version" 2> /dev/null || :)"
  version="${version:-$latest_version}"

  if [ -z "$current_version" ]; then
    version="$latest_version"
  elif [ "$current_version" = "$latest_version" ]; then
    return 0
  else
    echo "=> New runner version is available."
  fi

  if [[ "$RUNNER_ARCH" = "amd64" || "$RUNNER_ARCH" = "x86_64" ]]; then arch=x64 ; fi
  echo -n "=> Installing github actions runner version $version... "
  mkdir -p /tmp/runnerdist
  curl -sL "https://github.com/actions/runner/releases/download/v${version}/actions-runner-linux-${arch}-${version}.tar.gz" | tar xzC /tmp/runnerdist
  chown -R runner:runner /tmp/runnerdist && mv -f /tmp/runnerdist/* "$RUNNER_HOME"
  echo -n "$version" > "$RUNNER_HOME/.version" && echo "done."
}

install_runner "$RUNNER_VERSION"
