name: Publish Images

on:
  workflow_dispatch:
  push:
    paths:
      - images/*.containerfile

env:
  REGISTRY: ghcr.io
  IMAGE_BASE: ${{ github.repository_owner }}/actions-runner

jobs:
  build:
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
        - file: ubuntu-22.04
          image: ubuntu
          tags: ["22.04"]
        - file: node-22
          image: node
          tags: ["22", "latest"]
        - file: gitops
          image: gitops
          tags: ["latest"]
        - file: ubuntu-24.04
          image: ubuntu
          tags: ["24.04", "latest"]
        - file: alpine
          image: alpine
          tags: ["3", "3.20", "latest"]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: tags
        uses: actions/github-script@v7
        with:
          script: |
            let json = `${{ toJSON(matrix.tags) }}`
            core.setOutput("multiline", JSON.parse(json).join("\n"))

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}/images/${{ matrix.image }}
          tags: |
            ${{ steps.tags.outputs.multiline }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: ./images
          file: images/${{ matrix.file }}.containerfile
          platforms: |
            linux/amd64
          labels: |
            ${{ steps.meta.outputs.labels }}
          tags: |
            ${{ steps.meta.outputs.tags }}
          push: ${{ github.ref == 'refs/heads/master' }}
